/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SymptomTrackingRouteImport } from './routes/symptom-tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomTrackingRoute = SymptomTrackingRouteImport.update({
  id: '/symptom-tracking',
  path: '/symptom-tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/medications': typeof MedicationsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/symptom-tracking': typeof SymptomTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/medications': typeof MedicationsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/symptom-tracking': typeof SymptomTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/medications': typeof MedicationsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/symptom-tracking': typeof SymptomTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communication'
    | '/medications'
    | '/reminders'
    | '/settings'
    | '/symptom-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communication'
    | '/medications'
    | '/reminders'
    | '/settings'
    | '/symptom-tracking'
  id:
    | '__root__'
    | '/'
    | '/communication'
    | '/medications'
    | '/reminders'
    | '/settings'
    | '/symptom-tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunicationRoute: typeof CommunicationRoute
  MedicationsRoute: typeof MedicationsRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  SymptomTrackingRoute: typeof SymptomTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-tracking': {
      id: '/symptom-tracking'
      path: '/symptom-tracking'
      fullPath: '/symptom-tracking'
      preLoaderRoute: typeof SymptomTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunicationRoute: CommunicationRoute,
  MedicationsRoute: MedicationsRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  SymptomTrackingRoute: SymptomTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
